language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '7'
  - '6'
before_script:
  - npm prune
script:
  - npm run test:coverage
  - npm run coverage:check
after_success:
  - npm run codecov
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
